#!/usr/bin/env bash
#
# PreToolUse hook — refuse writes to paths that must never be edited by hand.
#
#   dist/**         build output; `pnpm build` overwrites it. Editing the copy
#                   of _redirects/_headers that lives there looks like it works
#                   and is silently erased on the next build.
#   pnpm-lock.yaml  a lockfile change means a dependency change, and AGENTS.md
#                   golden rule 11 requires explicit user approval for those.
#   .env            secrets (e.g. CLOUDFLARE_API_TOKEN) — gitignored, hands off.
#
# Exit 2 blocks the tool call and shows stderr to Claude.

set -uo pipefail

payload="$(cat)"
file="$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty')"
[ -n "$file" ] || exit 0

root="${CLAUDE_PROJECT_DIR:-$PWD}"
rel="${file#"$root"/}"

case "$rel" in
  dist/*)
    cat >&2 <<'MSG'
Blocked: dist/ is build output and is regenerated by `pnpm build`.
Edit the source instead:
  - SPA fallback           -> public/_redirects
  - cache/security headers -> public/_headers
Vite copies public/ verbatim into dist/analog/public.
MSG
    exit 2
    ;;
  pnpm-lock.yaml)
    cat >&2 <<'MSG'
Blocked: pnpm-lock.yaml is only written by pnpm itself, and a lockfile change
means a dependency change. AGENTS.md golden rule 11: no new dependencies
without explicit user approval. Ask first, then let the user run `pnpm add`.
MSG
    exit 2
    ;;
  .env|.env.*)
    echo "Blocked: $rel holds secrets and is gitignored. Ask the user to edit it." >&2
    exit 2
    ;;
esac

exit 0
