import { Component, Injectable  } from "@angular/core";
import { buildPrintStylesheet } from "./print-stylesheet";

/**
 * Browser-native PDF export using `window.print()`.
 *
 * ## How it works
 *
 * 1. Clone `#resume-content` into a wrapper `<div>` at `<body>` root level.
 *    Because the clone lives in the **same document**, Angular's scoped
 *    styles (`_ngcontent-*` attributes) continue to match.
 *
 * 2. Inject an `@media print` stylesheet that:
 *    - hides every `<body>` child except the wrapper,
 *    - forces the resume to A4 dimensions (210 mm × 297 mm),
 *    - preserves background colours/gradients.
 *
 * 3. Call `window.print()` — the browser shows its native print dialog.
 *
 * 4. After the dialog closes, remove the wrapper and stylesheet.
 *
 * ## Design rationale
 *
 * - **No new tab/window** — avoids pop-up blockers and UX friction.
 * - **No DOM-style inlining** — percentage / flex layouts stay responsive.
 * - **Stylesheet is generated by `buildPrintStylesheet()`** so the CSS
 *   logic is unit-testable and follows Single Responsibility.
 */
@Injectable({ providedIn: "root" })
export class PrintExport {
  /**
   * Opens the browser's print dialog with only the resume visible,
   * rendered at full A4 dimensions.
   *
   * @param element The `#resume-content` DOM node to print.
   */
  async printResume(element: HTMLElement): Promise<void> {
    const { wrapper, style } = this.preparePrintDOM(element);

    // Allow the browser one frame to lay out the injected nodes
    await this.waitForRender();

    window.print();

    this.cleanup(wrapper, style);
  }

  // ─── Private helpers ─────────────────────────────────────────

  /**
   * Clone the resume element into a body-level wrapper
   * and inject the print stylesheet.
   */
  private preparePrintDOM(element: HTMLElement): {
    wrapper: HTMLElement;
    style: HTMLStyleElement;
  } {
    const wrapper = document.createElement("div");
    wrapper.id = "print-wrapper";
    wrapper.appendChild(element.cloneNode(true));
    document.body.appendChild(wrapper);

    const style = document.createElement("style");
    style.id = "print-styles";
    style.textContent = buildPrintStylesheet();
    document.head.appendChild(style);

    return { wrapper, style };
  }

  /** Yield to the browser so the newly injected DOM is laid out. */
  private waitForRender(): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, 50));
  }

  /** Remove injected DOM nodes, restoring the page to its original state. */
  private cleanup(wrapper: HTMLElement, style: HTMLStyleElement): void {
    wrapper.remove();
    style.remove();
  }
}
